p8105_hw2_xx2554
================
Xinyan Xu
2026-10-05

``` r
library(tidyverse)
library(readxl)
```

## Problem 1

``` r
transit_df = 
  read_csv(
    "./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
    col_types = cols(
      Route8 = col_character(),
      Route9 = col_character(),
      Route10 = col_character(),
      Route11 = col_character()
    )
  ) |> 
  janitor::clean_names() |> 
  select(
    line, station_name, station_latitude, station_longitude,
    starts_with("route"), entry, vending, entrance_type, ada
  ) |> 
  mutate(
    entry = case_match(
      entry,
      "YES" ~ TRUE,
      "NO" ~ FALSE
    ))
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `entry = case_match(entry, "YES" ~ TRUE, "NO" ~ FALSE)`.
    ## Caused by warning:
    ## ! `case_match()` was deprecated in dplyr 1.2.0.
    ## ℹ Please use `recode_values()` instead.

``` r
transit_df
```

    ## # A tibble: 1,868 × 19
    ##    line     station_name station_latitude station_longitude route1 route2 route3
    ##    <chr>    <chr>                   <dbl>             <dbl> <chr>  <chr>  <chr> 
    ##  1 4 Avenue 25th St                  40.7             -74.0 R      <NA>   <NA>  
    ##  2 4 Avenue 25th St                  40.7             -74.0 R      <NA>   <NA>  
    ##  3 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  4 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  5 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  6 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  7 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  8 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  9 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ## 10 4 Avenue 53rd St                  40.6             -74.0 R      <NA>   <NA>  
    ## # ℹ 1,858 more rows
    ## # ℹ 12 more variables: route4 <chr>, route5 <chr>, route6 <chr>, route7 <chr>,
    ## #   route8 <chr>, route9 <chr>, route10 <chr>, route11 <chr>, entry <lgl>,
    ## #   vending <chr>, entrance_type <chr>, ada <lgl>

This dataset contains information on each entrance and exit of the NYC
subway system, so each row represents one entrance or exit rather than
one station. The cleaned dataset includes line, station name, station
latitude and longitude, the routes served (`route1` to `route11`),
entry, vending, entrance type, and ADA compliance. To clean the data, I
imported the CSV using a relative path (reading `route8` to `route11` as
character so all route columns have the same type), cleaned variable
names with `janitor::clean_names()`, kept the variables of interest with
`select`, and converted `entry` from `YES`/`NO` to a logical variable
using `case_match`. The resulting dataset has 1868 rows and 19 columns.
These data are not tidy: route served is a single variable, but it is
spread across 11 columns with the route number stored in the column
names, and most of these columns are missing because most stations serve
only a few routes.

### Distinct stations

``` r
n_stations = 
  transit_df |> 
  distinct(line, station_name) |> 
  nrow()
```

There are 465 distinct stations, identified by both station name and
line.

### ADA compliant stations

``` r
n_ada_stations = 
  transit_df |> 
  filter(ada == TRUE) |> 
  distinct(line, station_name) |> 
  nrow()
```

84 stations are ADA compliant.

### Entrances without vending that allow entrance

``` r
prop_entry_no_vending = 
  transit_df |> 
  filter(vending == "NO") |> 
  pull(entry) |> 
  mean()
```

Among station entrances / exits without vending (counted at the entrance
level, not the station level), 37.7% allow entrance.

### Reformatting routes

``` r
transit_tidy_df = 
  transit_df |> 
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    names_prefix = "route",
    values_to = "route_name") |> 
  drop_na(route_name) |> 
  mutate(route_number = as.numeric(route_number))

transit_tidy_df
```

    ## # A tibble: 4,270 × 10
    ##    line     station_name station_latitude station_longitude entry vending
    ##    <chr>    <chr>                   <dbl>             <dbl> <lgl> <chr>  
    ##  1 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ##  2 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ##  3 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ##  4 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ##  5 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ##  6 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ##  7 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ##  8 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ##  9 4 Avenue 45th St                  40.6             -74.0 TRUE  YES    
    ## 10 4 Avenue 45th St                  40.6             -74.0 TRUE  YES    
    ## # ℹ 4,260 more rows
    ## # ℹ 4 more variables: entrance_type <chr>, ada <lgl>, route_number <dbl>,
    ## #   route_name <chr>

The reformatted dataset has one row for each route served at each
entrance / exit, with `route_number` and `route_name` as separate
variables (4270 rows and 10 columns).

### Stations serving the A train

``` r
n_a_stations = 
  transit_tidy_df |> 
  filter(route_name == "A") |> 
  distinct(line, station_name) |> 
  nrow()

n_a_ada_stations = 
  transit_tidy_df |> 
  filter(route_name == "A", ada == TRUE) |> 
  distinct(line, station_name) |> 
  nrow()
```

60 distinct stations serve the A train, and 17 of these are ADA
compliant.
